mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
mod 'biemond-wildfly', '2.3.2'
mod 'jethrocarr-initfact', '1.0.1'
